### ISSUE TITLE
Circle with negative radius moves incorrectly and fails to draw.

### ISSUE THREAD

**Issue by nickovs** [boyuai/ipyturtle2#9]
The `circle()` method for a Turtle is [defined](https://docs.python.org/3/library/turtle.html#turtle.circle) take have a centre position that is `radius` units to the left of the turtle's current position; when `radius` is positive the circle should proceed in the counterclockwise direction and when `radius` is negative the circle should proceed clockwise.

The current implementation of `circle()` fails in two distinct ways:

- When `radius` is negative the turtle ends up in the wrong position after the command.
- When `radius` is negative no arc or circle is drawn.

The first issue appears to be to do with the [Python `circle()` method](https://github.com/boyuai/ipyturtle2/blob/c2aa89257885835abca9a6991764d87ed6abb0b9/ipyturtle2/example.py#L248) does not invert the sign of the extent when the `radius` is negative. I'm not certain what the cause of the second problem is.

**Comment by cqby** [comment]
fix 0.8.1
